# Generated by Django 3.1.1 on 2020-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='infection_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
