# Generated by Django 3.1.1 on 2020-09-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200911_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='infection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
