# Generated by Django 3.1.1 on 2020-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200911_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuids',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
