# Generated by Django 3.1.2 on 2020-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200916_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
