# Generated by Django 3.1.2 on 2020-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201021_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_infection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uncontact',
            field=models.BooleanField(default=False),
        ),
    ]
