# Generated by Django 3.1.2 on 2020-10-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201022_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unconfirmed_infected',
            new_name='unconfirmed_contact',
        ),
    ]
