# Generated by Django 3.1.2 on 2020-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201022_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uncontact',
            new_name='unconfirmed_infected',
        ),
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
